---
name: Prettify, lint and test

on:
  pull_request:
  push:
    branches:
      - master
      - update-script

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pre-commit
        uses: pre-commit/action@v3.0.0

      # TODO: Replace with pre-commit hook
      - name: Prettify source.yaml
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write source.yaml
          file_pattern: source.yaml

  test:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install --with=dev

      - name: Run Ruff
        run: poetry run ruff --format=github .

      - name: Run tests
        run: poetry run pytest --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
