---
name: Test and lint

on:
  pull_request:
  push:
    branches:
      - master
      - update-script

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: poetry install --with=dev

      - name: Run Ruff
        run: poetry run ruff --format=github .

      - name: Run tests
        run: poetry run pytest
