---
name: Update streams

on:
  push:
    branches:
      - master
      - update-script
    paths:
      - sources/radio.yaml
      - sources/tv.yaml

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      IPTV_OUTPUT_DIR: iptv
      LOGO_BASE_PATH: https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/ # yamllint disable-line
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install kodinerds-iptv tool
        run: pipx install .

      - name: Update IPTV lists
        run: kn-iptv generate --output-dir "$IPTV_OUTPUT_DIR" --logo-base-path "$LOGO_BASE_PATH" sources/tv.yaml sources/radio.yaml # yamllint disable-line

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Update Bot
          author_email: update-bot@example.com
          message: "Update .m3u files"
          add: "iptv/*.m3u"
