---
name: Update .m3u files

on:
  push:
    branches:
      - master
      - update-script
    paths:
      - source.yaml

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update IPTV lists
        run: src/generate_lists.py \
          --destination iptv \
          --image_base_path https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/ \
          source.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Update Bot
          author_email: update-bot@example.com
          message: "Update .m3u files"
          add: "iptv/*.m3u"
